### NAME :- Pranit Dutta
### CWID :- 20010681

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,recall_score,f1_score,precision_score


In [2]:
data_train=pd.read_csv("train.csv")
data_train.head(5)

x         y         z  class
0  8.599291  9.729418  6.432371      1
1  6.592955  0.082556  1.969544      1
2  5.596471  9.815682  0.027295      1
3  2.743639  8.783177  4.041946      0
4  4.458362  5.750222  0.099070      0

In [3]:
data_test=pd.read_csv("test.csv")
data_test.head(5)

ID         x         y         z  actual-class
0   1  8.074807  5.988044  3.844979             1
1   2  4.952249  5.823205  1.612045             0
2   3  4.773178  0.078757  4.209442             0
3   4  9.845919  2.055448  3.525702             1
4   5  1.612492  1.320515  8.200455             0

In [4]:
X_train=data_train.iloc[:,:-1]
y_train=data_train.iloc[:,-1]

In [5]:
X_test=data_test.iloc[:,1:-1]
y_test=data_test.iloc[:,-1]

### Part 1

In [6]:
model=KNeighborsClassifier(n_neighbors=3)

In [7]:
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [8]:
pred_train=model.predict(X_train)

In [9]:
pred_test=model.predict(X_test)

In [10]:
pred_prob=model.predict_proba(X_test)

In [11]:
pred_prob

array([[0.        , 1.        ],
       [0.66666667, 0.33333333],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.33333333, 0.66666667],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ]])

In [12]:
model.kneighbors(X_test)

(array([[0.47114706, 0.75897499, 0.78958855],
        [0.73371497, 0.83351774, 0.89627508],
        [0.98552101, 1.01034719, 1.31331704],
        [0.94044961, 1.03585696, 1.10146319],
        [0.60759399, 0.65093284, 0.66237823],
        [0.54036277, 0.73300549, 0.78592856],
        [0.40740298, 0.75010519, 0.92830109],
        [0.40676278, 0.45537183, 0.96325276],
        [0.65278514, 0.74460626, 0.93488309],
        [0.10903051, 0.41226267, 0.49350556],
        [0.84398112, 1.19621597, 1.19856366],
        [0.32388786, 0.33312069, 0.6905615 ],
        [0.72518831, 0.77862394, 0.84069725],
        [0.45370987, 0.72255863, 0.72750999],
        [0.68178815, 0.75328445, 0.89713298],
        [0.50719005, 0.56015606, 0.73992137],
        [0.7118834 , 0.73956702, 0.9625313 ],
        [0.70540913, 0.72669453, 0.78546744],
        [0.18726799, 0.33658159, 0.70592577],
        [0.53833095, 0.57717476, 0.67621262]]),
 array([[187, 404, 784],
        [516,  48, 743],
        [283, 842, 450],
   

In [13]:
pred=pd.DataFrame({"Actual":y_test,"Predicted":pred_test})

In [14]:
pred

Actual  Predicted
0        1          1
1        0          0
2        0          0
3        1          1
4        0          0
5        1          1
6        0          0
7        0          0
8        0          0
9        0          0
10       1          1
11       0          0
12       0          0
13       0          0
14       0          1
15       1          1
16       1          1
17       0          0
18       0          0
19       0          0

Classification report on Training 

In [15]:
print(classification_report(y_train,pred_train))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96       624
           1       0.95      0.92      0.93       376

    accuracy                           0.95      1000
   macro avg       0.95      0.94      0.95      1000
weighted avg       0.95      0.95      0.95      1000



In [16]:
print(confusion_matrix(y_test,pred_test))

[[13  1]
 [ 0  6]]


For training 

In [17]:
print(classification_report(y_test,pred_test))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.86      1.00      0.92         6

    accuracy                           0.95        20
   macro avg       0.93      0.96      0.94        20
weighted avg       0.96      0.95      0.95        20



In [18]:
print(confusion_matrix(y_test,pred_test))

[[13  1]
 [ 0  6]]


In [19]:
print("Accuracy for test set is :- ",accuracy_score(y_test,pred_test))
print("Precission for test set is :- ",precision_score(y_test,pred_test))
print("F1 for test set is :- ",f1_score(y_test,pred_test))

Accuracy for test set is :-  0.95
Precission for test set is :-  0.8571428571428571
F1 for test set is :-  0.923076923076923


### Part 2

In [20]:
model1=KNeighborsClassifier(n_neighbors=3,metric='euclidean',weights='distance')


In [21]:
model1.fit(X_train,y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=3, weights='distance')

In [22]:
pred_test1=model1.predict(X_test)

In [23]:
print(classification_report(y_test,pred_test1))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.86      1.00      0.92         6

    accuracy                           0.95        20
   macro avg       0.93      0.96      0.94        20
weighted avg       0.96      0.95      0.95        20



In [24]:
print(confusion_matrix(y_test,pred_test1))

[[13  1]
 [ 0  6]]


In [25]:
print("Accuracy for test set (euclidian) is :- ",accuracy_score(y_test,pred_test1))
print("Precission for test set (euclidian) is :- ",precision_score(y_test,pred_test1))
print("F1 for test set is (euclidian) :- ",f1_score(y_test,pred_test1))

Accuracy for test set (euclidian) is :-  0.95
Precission for test set (euclidian) is :-  0.8571428571428571
F1 for test set is (euclidian) :-  0.923076923076923


### Part 3

In [26]:
print("Accuracy for test set (euclidian) is :- ",accuracy_score(y_test,pred_test1))
print("Accuracy for test set knn is :- ",accuracy_score(y_test,pred_test))

Accuracy for test set (euclidian) is :-  0.95
Accuracy for test set knn is :-  0.95


In [27]:
print("Precission for test set (euclidian) is :- ",precision_score(y_test,pred_test1))
print("Precission for test set knn is :- ",precision_score(y_test,pred_test))

Precission for test set (euclidian) is :-  0.8571428571428571
Precission for test set knn is :-  0.8571428571428571


In [28]:
print("F1 for test set is (euclidian) :- ",f1_score(y_test,pred_test1))
print("F1 for test set is knn :- ",f1_score(y_test,pred_test))

F1 for test set is (euclidian) :-  0.923076923076923
F1 for test set is knn :-  0.923076923076923


##### Since the dataset extremely small, both of the models perform same. If dataset was huge maybe one of them would have been better, and my guess would have been the weighted KNN would've been more accurate #####